      IA=0
      PRINT 1
   1  FORMAT (/34HTHIS CODE SUMS THE FIRST N NUMBERS//12HINTRODUCE N:)
      READ 2, N
   2  FORMAT (I3) 
      DO 3, I=1,N
      IA = IA+I
   3  CONTINUE
      PRINT 4, N, IA
   4  FORMAT (21HTHE SUM OF THE FIRST I3,12H NUMBERS IS I4)
      END