C     MATRIXES HAVE TO BE DECLARED HERE?
      DIMENSION IC(3)
      DIMENSION B(3)
      IA = 5
      IB = 5
      PRINT 1, IA, IB
C     ITS IMPORTANT TO WRITE THE FORMAT CORRECTLY  
   1  FORMAT (12HNUMBERS ARE 1I3,5H AND 1I3)
      FA = 5.5
      FB = 6.5
      PRINT 2, FA, FB
   2  FORMAT (28HSECOND BATCH OF NUMBERS ARE F3.1,5H AND F3.1)
      PRINT 3
   3  FORMAT (24HSPECIAL OUTPUTS AS WELL:)
      PRINT 4, IA, FA, IB
C     PAGE 30 OF THE MANUAL EXPLAINS THIS QUITE WELL  
   4  FORMAT (I3/F3.1/I3)
C     NOW, PRINTING A LIST
      PRINT 5
   5  FORMAT (16HNOW THE LAST ONE)
      DO 7, I=1,3
      IC(I) = I
   7  CONTINUE
      PRINT 6, (IC(J), J=1,3) 
   6  FORMAT (I1)
      END